### ISSUE TITLE
Cannot use CASE in my OQL query

### ISSUE THREAD

**Issue by gitsno** [ArjenLammers/oqlmodule#5]
When I use a CASE expression in my OQL query with the Execute OQL statement action the values in the THEN and the ELSE always get replaced with ? and the query fails. I tried using string literals or putting the values in parameters and either way it always fails because the the values are replaced with ? in the SQL that is generated.

So my query is like either of these:
```
'SELECT CASE WHEN GroupRequirement THEN ''Group'' ELSE ''Not group'' END AS GroupRequirement, count(*) AS RequirementCount
FROM Requirements.Requirement
GROUP BY GroupRequirement'
```
or I add parameters with the two strings and use this query
```
'SELECT CASE WHEN GroupRequirement THEN $Group ELSE $NotGroup END AS GroupRequirement , count(*) AS RequirementCount
FROM Requirements.Requirement
GROUP BY GroupRequirement'
```

Either way I see this in the exception:
```
Caused by: com.mendix.basis.connectionbus.ConnectionBusException: Exception occurred while retrieving data. (SQL State: 42567, Error Code: -5567) Detail Message: org.hsqldb.HsqlException: data type cast needed for parameter or null literal
	at com.mendix.connectionbus.connections.jdbc.JdbcDataStore.getCorrectException(JdbcDataStore.java:736)

Caused by: java.sql.SQLSyntaxErrorException: data type cast needed for parameter or null literal in statement [SELECT CASE WHEN "requirements$requirement"."grouprequirement" THEN ? ELSE ? END AS "GroupRequirement", 
COUNT(*) AS "RequirementCount"
 FROM "requirements$requirement"
 GROUP BY "GroupRequirement"]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
```

Is it a known issue with the Execute OQL statement action that you cannot use the CASE expression or does it require special syntax?

**Comment by gitsno** [comment]
I figured this out - sorry for the non-issue report.

In case anyone else sees this - you need to cast literal values, so in the query above just do this:
```
'SELECT CASE WHEN GroupRequirement THEN CAST(''Group'' AS STRING) ELSE CAST(''Not group'' AS STRING) END AS GroupRequirement, count(*) AS RequirementCount
FROM Requirements.Requirement
GROUP BY GroupRequirement'
```
